/**
 * BacktrackMCQ.jsx
 *
 * Renders all LLM-generated prerequisite MCQs in one card UI.
 * Replaces the old PrereqOnboarding component — questions are now
 * dynamic (generated by the backend per goal) instead of hardcoded.
 *
 * Props
 * -----
 *   mcqs     : Array<{ gap, question, options: {A,B,C} }>
 *   goal     : string  — shown in the card header
 *   onSubmit : fn(answers: object)  — called with { gap1: "A", gap2: "B", ... }
 */

import React, { useState } from "react";

function OptionChip({ label, text, selected, onClick }) {
  return (
    <button
      onClick={onClick}
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: 10,
        padding: "10px 14px",
        borderRadius: "var(--r-md, 8px)",
        border: selected
          ? "1.5px solid var(--blue, #4f8ef7)"
          : "1px solid var(--border, rgba(255,255,255,0.09))",
        background: selected
          ? "rgba(79,142,247,0.12)"
          : "var(--surface-2, #1a1a24)",
        color: selected ? "var(--text-primary, #e8e8f0)" : "var(--text-muted, #8888a4)",
        fontSize: 13,
        fontFamily: "var(--font, inherit)",
        cursor: "pointer",
        textAlign: "left",
        width: "100%",
        transition: "all 0.14s ease",
        boxShadow: selected ? "0 0 0 3px rgba(79,142,247,0.1)" : "none",
      }}
    >
      {/* Letter badge */}
      <span style={{
        minWidth: 22,
        height: 22,
        borderRadius: 6,
        border: selected ? "1.5px solid var(--blue, #4f8ef7)" : "1px solid var(--border-hi, rgba(255,255,255,0.15))",
        background: selected ? "var(--blue, #4f8ef7)" : "transparent",
        color: selected ? "white" : "var(--text-dim, #555570)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 11,
        fontWeight: 700,
        flexShrink: 0,
        marginTop: 1,
      }}>
        {label}
      </span>
      <span style={{ flex: 1, lineHeight: 1.5 }}>{text}</span>
    </button>
  );
}

function MCQCard({ mcq, index, total, answer, onSelect }) {
  return (
    <div style={{ marginBottom: index < total - 1 ? 24 : 0 }}>
      {/* Question header */}
      <div style={{
        display: "flex",
        alignItems: "baseline",
        gap: 8,
        marginBottom: 10,
      }}>
        <span style={{
          fontSize: 10,
          fontWeight: 700,
          color: "var(--text-dim, #555570)",
          fontFamily: "var(--mono, monospace)",
          letterSpacing: "0.06em",
          textTransform: "uppercase",
          flexShrink: 0,
        }}>
          {index + 1}/{total}
        </span>
        <p style={{
          fontSize: 13,
          fontWeight: 600,
          color: "var(--text-primary, #e8e8f0)",
          lineHeight: 1.5,
          margin: 0,
        }}>
          {mcq.question}
        </p>
      </div>

      {/* Options */}
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {Object.entries(mcq.options).map(([label, text]) => (
          <OptionChip
            key={label}
            label={label}
            text={text}
            selected={answer === label}
            onClick={() => onSelect(mcq.gap, label)}
          />
        ))}
      </div>

      {/* Divider between questions */}
      {index < total - 1 && (
        <div style={{
          marginTop: 20,
          borderBottom: "1px solid var(--border, rgba(255,255,255,0.06))",
        }} />
      )}
    </div>
  );
}

export default function BacktrackMCQ({ mcqs, goal, onSubmit }) {
  const [answers, setAnswers] = useState({});
  const [submitting, setSubmitting] = useState(false);

  const allAnswered = mcqs.every(m => answers[m.gap]);

  const select = (gap, label) => {
    setAnswers(prev => ({ ...prev, [gap]: label }));
  };

  const handleSubmit = async () => {
    if (!allAnswered || submitting) return;
    setSubmitting(true);
    await onSubmit(answers);
  };

  return (
    <div style={{
      background: "var(--surface-1, #13131c)",
      border: "1px solid var(--border-hi, rgba(255,255,255,0.1))",
      borderRadius: "var(--r-lg, 12px)",
      padding: "20px 22px",
      maxWidth: 520,
      width: "100%",
      boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
    }}>
      {/* Header */}
      <div style={{
        display: "flex",
        alignItems: "center",
        gap: 8,
        marginBottom: 18,
        paddingBottom: 14,
        borderBottom: "1px solid var(--border, rgba(255,255,255,0.06))",
      }}>
        <span style={{ fontSize: 15 }}>◎</span>
        <div>
          <div style={{
            fontSize: 11,
            fontWeight: 700,
            color: "var(--purple, #a855f7)",
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            fontFamily: "var(--mono, monospace)",
          }}>
            Prerequisite check
          </div>
          {goal && (
            <div style={{
              fontSize: 11,
              color: "var(--text-dim, #555570)",
              marginTop: 2,
            }}>
              For: {goal.length > 60 ? goal.slice(0, 60) + "…" : goal}
            </div>
          )}
        </div>

        {/* Progress pills */}
        <div style={{ marginLeft: "auto", display: "flex", gap: 4 }}>
          {mcqs.map((m, i) => (
            <div key={i} style={{
              width: answers[m.gap] ? 18 : 6,
              height: 6,
              borderRadius: 3,
              background: answers[m.gap] ? "var(--blue, #4f8ef7)" : "var(--surface-4, #2a2a3c)",
              transition: "all 0.25s ease",
            }} />
          ))}
        </div>
      </div>

      {/* All MCQ questions */}
      {mcqs.map((mcq, i) => (
        <MCQCard
          key={mcq.gap}
          mcq={mcq}
          index={i}
          total={mcqs.length}
          answer={answers[mcq.gap]}
          onSelect={select}
        />
      ))}

      {/* Submit */}
      <button
        onClick={handleSubmit}
        disabled={!allAnswered || submitting}
        style={{
          marginTop: 20,
          width: "100%",
          padding: "11px 20px",
          background: allAnswered ? "var(--blue, #4f8ef7)" : "var(--surface-4, #2a2a3c)",
          border: "none",
          borderRadius: "var(--r-md, 8px)",
          color: allAnswered ? "white" : "var(--text-dim, #555570)",
          fontSize: 13,
          fontWeight: 600,
          cursor: allAnswered ? "pointer" : "not-allowed",
          fontFamily: "var(--font, inherit)",
          transition: "all 0.15s",
          opacity: submitting ? 0.7 : 1,
        }}
      >
        {submitting
          ? "Building your plan…"
          : allAnswered
          ? `Build my plan →`
          : `Answer all ${mcqs.length} questions to continue`}
      </button>
    </div>
  );
}